# Generated by Django 4.2.7 on 2026-04-26 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher (0 years)'), ('junior', 'Junior (1-2 years)'), ('mid', 'Mid-level (3-5 years)'), ('senior', 'Senior (5+ years)')], default='fresher', max_length=20)),
                ('experience_years', models.IntegerField(default=0)),
                ('preferred_roles', models.TextField(blank=True, help_text='Comma-separated job titles')),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('resume_text', models.TextField(blank=True, help_text='Paste resume content for better matching')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
