# Generated by Django 4.2.7 on 2026-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_logo', models.URLField(blank=True, default='')),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
                ('location', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('category', models.CharField(choices=[('software', 'Software Engineering'), ('data', 'Data Science & ML'), ('design', 'Design & UX'), ('product', 'Product Management'), ('devops', 'DevOps & Cloud'), ('mobile', 'Mobile Development'), ('backend', 'Backend Development'), ('frontend', 'Frontend Development'), ('fullstack', 'Full Stack Development'), ('cybersecurity', 'Cybersecurity'), ('other', 'Other')], default='software', max_length=30)),
                ('experience_required', models.CharField(choices=[('fresher', 'Fresher'), ('1_2', '1-2 Years'), ('3_5', '3-5 Years'), ('5_plus', '5+ Years')], default='fresher', max_length=10)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
